"""

Revision ID: b1263027e476
Revises: b739fd026a81
Create Date: 2026-09-22 14:54:45.584650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1263027e476'
down_revision = 'b739fd026a81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_column('token')

    # ### end Alembic commands ###
